### PR TITLE
Resolve Issue #26 - Parsing objects within an array

### LINKED ISSUE #26: Parsing an array of one or more objects fails.
The following, simplest example fails.

`[ {} ]`

### PR DESCRIPTION
**Pull request by hockeyhurd**
See git log.

### CODE REVIEW

File: src/parser/parser.rs [hunk 1]
```diff
@@ -301,7 +313,8 @@ fn try_parse_object(parser: &mut Parser, token_in: Rc<dyn TokenTrait>) -> Option
                         {
                             nodes.insert(key, Rc::clone(&node_type));
                         },
-                        None => { println!("Error: expected to parse an RNode type at {0}", snapshot.to_string()); return None; },
+                        // None => { println!("Error: expected to parse an RNode type at {0}", snapshot.to_string()); return None; },
```
Comment (hockeyhurd) [inline src/parser/parser.rs]: Clean up

**Review by hockeyhurd — COMMENTED** [review]
See 1 review comment.
